### ISSUE TITLE
db container needs to be initialized before passbolt one

### ISSUE THREAD

**Issue by elboletaire** [dlen/passbolt-compose#1]
DB container initialization lasts longer than passbolt, and this brings a `connection refused` error in passbolt.

![imatge](https://user-images.githubusercontent.com/153305/30069860-1b3fd1e6-9262-11e7-93fa-dcbbc475c7ad.png)

To avoid it, the `passbolt` container should look for the db connection in the entrypoint.

https://docs.docker.com/compose/startup-order/

**Comment by dlen** [comment]
Hi @elboletaire thanks for your report. Yeah, it is a [known problem](https://docs.docker.com/compose/startup-order/) :( . There are few hacky solutions that could be bundled on the passbolt docker image but for now it's not on the roadmap. So I suggest just to launch the db service, wai until it is completely up and running and launch passbolt. This will remain this way until I find time to dig into it more.

**Comment by elboletaire** [comment]
Nice!
