### ISSUE TITLE
can't login to passbolt 

### ISSUE THREAD

**Issue by atefehzaker** [dlen/passbolt-compose#3]
Hello. I'm trying to use passbolt for my server. but when I go to my server's address, I get this message that I need an account to login. would you help me with that?
![screenshot from 2018-01-17 18-57-59](https://user-images.githubusercontent.com/33786114/35050591-6dadbd5c-fbb8-11e7-8120-8a794510bce8.png)

**Comment by dlen** [comment]
Hi @atefehzaker !
That means you need to activate the public registration on the container to create accounts freely (that would require you to set up an email sender account which is not covered by the passbolt-compose) using the environment variable  `REGISTRATION` Or you can connect to the running passbolt container and create an account as described in the https://www.passbolt.com/help/tech/install.

I encourage you to visit our community forum in case you have more questions: https://community.passbolt.com

**Comment by atefehzaker** [comment]
Thank you so much!
