### ISSUE TITLE
Error when accessing for the first time

### ISSUE THREAD

**Issue by felpin** [dlen/passbolt-compose#4]
After following the installation instructions, I get an error when accessing the URL

![image](https://user-images.githubusercontent.com/22778265/36306340-70f8947a-12fe-11e8-94d3-b6118a4b5e6a.png)

**Comment by dlen** [comment]
Hi!

yeah you are right it is due a change in the format of URL env var in passbolt_docker I had it fixed locally but forgot to push it. I will do it right away.

**Comment by dlen** [comment]
Thanks for the report!
